using System.Text;
using System.Text.RegularExpressions;
using CNIT455.VPN.Core;

namespace CNIT455.VPN.ConfigGenerators;

public enum ServerTemplate { LegacyIpsecMobile, L2tp, WireGuardSiteToSite, OpenVpnSiteToSite, Ikev2, IpsecSiteToSite, PfSenseIpsec, PfSenseOpenVpn, PfSenseWireGuard }
public sealed class ServerConfigOptions
{
    public ServerTemplate Template { get; set; } = ServerTemplate.LegacyIpsecMobile;
    public string VyosVersion { get; set; } = "1.5";
    public string ExternalInterface { get; set; } = "eth0";
    public string ExternalAddress { get; set; } = "";
    public string PeerEndpoint { get; set; } = "";
    public string TunnelInterface { get; set; } = "wg0";
    public string LocalTunnelAddress { get; set; } = "10.255.10.1/30";
    public string PeerTunnelAddress { get; set; } = "10.255.10.2/30";
    public string LocalNetwork { get; set; } = "";
    public string RemoteNetwork { get; set; } = "";
    public string ClientPool { get; set; } = "10.255.20.0/24";
    public string GatewayAddress { get; set; } = "10.255.20.1";
    public string DnsServer { get; set; } = "";
    public AuthBackend Authentication { get; set; } = AuthBackend.LocalTest;
    public string Username { get; set; } = "labuser";
    public string RadiusServer { get; set; } = "";
    public string RadiusSourceAddress { get; set; } = "";
    public int RadiusPort { get; set; } = 1812;
    public string Domain { get; set; } = "";
    public string LdapServer { get; set; } = "";
    public string LdapBaseDn { get; set; } = "";
    public string LdapBindDn { get; set; } = "";
    public string AllowedGroup { get; set; } = "";
    public int Port { get; set; } = 51820;
    public string PeerPublicKey { get; set; } = "";
    public string CaName { get; set; } = "lab-ca";
    public string CertificateName { get; set; } = "vpn-client";
    public string ServerIdentity { get; set; } = "";
    public string IkeEncryption { get; set; } = "aes256";
    public string IkeHash { get; set; } = "sha256";
    public int DhGroup { get; set; } = 14;
    public string EspEncryption { get; set; } = "aes256";
    public string EspHash { get; set; } = "sha256";
    public int NatExemptionRule { get; set; } = 90;
    public List<string> Routes { get; set; } = [];
}
public sealed record GeneratedConfiguration(string Title, string Text, IReadOnlyList<string> Warnings, bool Supported);

/// <summary>Preview only. Never executes commands or edits VyOS-managed strongSwan files.</summary>
public static class ServerConfigGenerator
{
    public static IReadOnlyList<string> SupportedVersions => ["1.4", "1.5"];
    public static GeneratedConfiguration Generate(ServerConfigOptions o, LabTopology topology)
    {
        if (o.Template is ServerTemplate.PfSenseIpsec or ServerTemplate.PfSenseOpenVpn or ServerTemplate.PfSenseWireGuard)
            return PfSense(o, topology);
        if (!KnownVersion(o.VyosVersion)) return Unsupported(o, "This VyOS version has no reviewed template. Run show version and select 1.4 or 1.5 only when it matches. Rolling/custom builds require review against their exact schema; no commands generated.");
        if (o.Template == ServerTemplate.LegacyIpsecMobile)
            return Unsupported(o, "No reviewed VyOS 1.4/1.5 CLI recipe establishes the requested PSK + IKEv1/XAUTH + Mode Config mobile service. The documented remote-access service is IKEv2 with X.509 server authentication. It is not an equivalent substitute for this lab. Obtain the instructor's exact VyOS image and supported configuration. Legacy/external strongSwan configuration may be required by the course design; this app will not modify files generated by VyOS. Confirm IKE version, exchange mode, peer ID, XAUTH, Mode Config, NAT-T and split networks with that image before using an imported Shrew profile.");
        var problems = Validate(o, topology);
        if (problems.Count > 0) return Unsupported(o, string.Join(Environment.NewLine, problems));
        try
        {
            var text = o.Template switch
            {
                ServerTemplate.L2tp => L2tp(o, topology),
                ServerTemplate.WireGuardSiteToSite => WireGuard(o, topology),
                ServerTemplate.OpenVpnSiteToSite => OpenVpn(o, topology),
                ServerTemplate.Ikev2 => Ikev2(o),
                ServerTemplate.IpsecSiteToSite => Ipsec(o, topology),
                _ => throw new ArgumentOutOfRangeException(nameof(o.Template))
            };
            return new(o.Template.ToString(), text, ["Preview contains secret placeholders. Fill them on the target router; do not paste secrets into evidence.", "Review existing firewall/NAT rule numbers and both return paths before applying. No configuration was sent."], true);
        }
        catch (ArgumentException ex) { return Unsupported(o, ex.Message); }
    }

    public static string DiagnosticCommands(ServerConfigOptions o)
    {
        if (!KnownVersion(o.VyosVersion)) return "# No verified diagnostic command set for this version.\nshow version\n";
        if (!GeneratorValidation.Token(o.TunnelInterface)) return "# Enter a valid tunnel interface name first.\nshow version\n";
        var text = new StringBuilder("# Operational mode (not configure). Output may identify users; inspect before sharing.\nshow version\nshow ip route\n");
        switch (o.Template)
        {
            case ServerTemplate.WireGuardSiteToSite:
                text.AppendLine($"show interfaces wireguard {o.TunnelInterface} summary");
                break;
            case ServerTemplate.OpenVpnSiteToSite:
                text.AppendLine("show openvpn client");
                break;
            case ServerTemplate.L2tp:
                text.AppendLine("show l2tp-server sessions").AppendLine("show l2tp-server statistics");
                text.AppendLine("show vpn ike sa").AppendLine("show vpn ipsec sa");
                break;
            case ServerTemplate.Ikev2:
                text.AppendLine("show vpn ipsec remote-access summary");
                text.AppendLine("show vpn ike sa").AppendLine("show vpn ipsec sa");
                break;
            default:
                text.AppendLine("show vpn ike sa").AppendLine("show vpn ipsec sa");
                break;
        }
        text.AppendLine("# Review firewall counters/NAT and logs in the router UI/CLI for your exact release.");
        text.AppendLine("# Do not share show configuration commands: it can expose credentials and keys.");
        return text.ToString();
    }

    private static bool KnownVersion(string version) => Regex.IsMatch(version, @"\A1\.(4|5)(\.[0-9]+)?\z");
    private static GeneratedConfiguration Unsupported(ServerConfigOptions o, string why) => new(o.Template.ToString(), $"NOT GENERATED\n\n{why}\n\nReference: https://docs.vyos.io/en/1.5/configuration/vpn/ipsec/remoteaccess_ipsec.html\n", [why], false);
    private static string Q(string value) => GeneratorValidation.Q(value);
    private static string Ip(string address) => address.Split('/')[0];
    private static string Pick(string value, string fallback) => string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();
    private static StringBuilder Header(ServerConfigOptions o, string source) => new StringBuilder()
        .AppendLine($"# Reviewed template: VyOS {o.VyosVersion}; source: https://docs.vyos.io/en/{(o.VyosVersion.StartsWith("1.4") ? "1.4" : "1.5")}/{source}")
        .AppendLine("# Review existing state and replace every <PLACEHOLDER>. No automatic execution.")
        .AppendLine("# Retain console access. In configure mode, inspect compare; commit only after review, then save.")
        .AppendLine("configure");
    private static void End(StringBuilder b) => b.AppendLine("compare").AppendLine("# After reviewing and replacing placeholders: commit").AppendLine("# After successful commit and validation: save");

    private static List<string> Validate(ServerConfigOptions o, LabTopology t)
    {
        var errors = new List<string>();
        // Validate the effective topology too: editable defaults are not trusted command fragments.
        foreach (var value in new[] { t.VyosHq, t.VyosRemote, t.VyosDmz, t.PfSenseHq, t.PfSenseRemote, t.PfSenseDmz })
            if (!Network(value)) errors.Add("Topology networks must be non-default IPv4 CIDRs with no host bits. These server templates do not generate IPv6 routing/NAT.");
        if (!GeneratorValidation.Ipv4(t.VyosExternal)) errors.Add("Topology VyOS endpoint must be IPv4.");
        if (!Enum.IsDefined(o.Template) || !Enum.IsDefined(o.Authentication)) errors.Add("Select a defined server template and authentication mode.");
        foreach (var (name, value) in new[] { ("External interface", o.ExternalInterface), ("Tunnel interface", o.TunnelInterface), ("Username", o.Username), ("CA name", o.CaName), ("Certificate name", o.CertificateName) })
            if (!GeneratorValidation.Token(value)) errors.Add($"{name}: use a nonempty alphanumeric identifier (._@- permitted).");
        if (!string.IsNullOrWhiteSpace(o.ExternalAddress) &&
            !(GeneratorValidation.Ipv4(o.ExternalAddress) || GeneratorValidation.Cidr(o.ExternalAddress) && GeneratorValidation.Ipv4(Ip(o.ExternalAddress)))) errors.Add("External address must be IPv4, optionally with a valid prefix length.");
        foreach (var (name, value) in new[] { ("Local network", o.LocalNetwork), ("Remote network", o.RemoteNetwork), ("Client pool", o.ClientPool) })
            if (!string.IsNullOrWhiteSpace(value) && !Network(value)) errors.Add($"{name}: use a non-default IPv4 network CIDR with no host bits. IPv6 server templates are not implemented.");
        foreach (var address in new[] { o.LocalTunnelAddress, o.PeerTunnelAddress })
            if (!GeneratorValidation.Cidr(address) || !GeneratorValidation.Ipv4(Ip(address))) errors.Add("Tunnel addresses must use IPv4 CIDR notation for these server templates.");
        if (o.Routes.Any(x => !Network(x))) errors.Add("Every additional route must be a non-default IPv4 network CIDR without host bits.");
        if (o.Port is < 1 or > 65535 || o.RadiusPort is < 1 or > 65535) errors.Add("Ports must be 1-65535.");
        if (o.NatExemptionRule is < 1 or > 999999 || (long)o.NatExemptionRule + o.Routes.Count > 999999) errors.Add("NAT exemption rule range must fit within 1-999999.");
        if (o.Template is ServerTemplate.WireGuardSiteToSite or ServerTemplate.OpenVpnSiteToSite or ServerTemplate.IpsecSiteToSite)
        {
            if (!GeneratorValidation.Host(o.PeerEndpoint)) errors.Add("Enter the other router's actual public endpoint; the assignment does not specify distinct HQ/Remote endpoints.");
            if (Ip(Pick(o.ExternalAddress, t.VyosExternal)) == o.PeerEndpoint) errors.Add("Local and peer public addresses must identify different routers.");
            var local = Pick(o.LocalNetwork, o.Template == ServerTemplate.OpenVpnSiteToSite ? t.VyosDmz : t.VyosHq);
            var remote = Pick(o.RemoteNetwork, o.Template == ServerTemplate.OpenVpnSiteToSite ? t.PfSenseDmz : t.VyosRemote);
            if (CidrNetwork.TryParse(local, out var lan))
                foreach (var network in new[] { remote }.Concat(o.Routes))
                    if (CidrNetwork.TryParse(network, out var destination) && lan.Overlaps(destination))
                        errors.Add("Local LAN and remote permitted networks must not overlap.");
        }
        if (o.Template == ServerTemplate.WireGuardSiteToSite)
        {
            if (!Regex.IsMatch(o.TunnelInterface, @"^wg\d+$")) errors.Add("WireGuard interface must be wg followed by a number.");
            if (!GeneratorValidation.Cidr(o.LocalTunnelAddress) || !GeneratorValidation.Cidr(o.PeerTunnelAddress)) errors.Add("Both WireGuard tunnel addresses require CIDR notation.");
            if (Ip(o.LocalTunnelAddress) == Ip(o.PeerTunnelAddress)) errors.Add("WireGuard peers require different tunnel addresses.");
            if (!string.IsNullOrWhiteSpace(o.PeerPublicKey) && !GeneratorValidation.Key(o.PeerPublicKey)) errors.Add("Peer public key must decode to 32 bytes.");
            if (CidrNetwork.TryParse(o.LocalTunnelAddress, out var localTunnel) && CidrNetwork.TryParse(o.PeerTunnelAddress, out var peerTunnel) && localTunnel != peerTunnel)
                errors.Add("Both WireGuard tunnel addresses must share the same IPv4 subnet and prefix length.");
        }
        if (o.Template == ServerTemplate.OpenVpnSiteToSite && !Regex.IsMatch(o.TunnelInterface, @"^vtun\d+$")) errors.Add("OpenVPN interface must be vtun followed by a number.");
        if (o.Template is ServerTemplate.L2tp or ServerTemplate.Ikev2)
        {
            if (!Network(o.ClientPool)) errors.Add("Client pool must be a non-default IPv4 network CIDR.");
            errors.AddRange(ProfileValidator.ValidatePool(o.ClientPool, new[] { Pick(o.LocalNetwork, t.VyosHq), t.VyosRemote, t.VyosDmz, t.PfSenseHq, t.PfSenseRemote, t.PfSenseDmz }).Select(x => x.Message));
            if (!GeneratorValidation.Ipv4(o.GatewayAddress)) errors.Add("Gateway address must be IPv4.");
            if (!string.IsNullOrWhiteSpace(o.DnsServer) && !GeneratorValidation.Ipv4(o.DnsServer)) errors.Add("DNS server must be IPv4 for this template.");
            if (o.Authentication == AuthBackend.Radius && !GeneratorValidation.Ipv4(o.RadiusServer)) errors.Add("Enter the RADIUS server IPv4 address.");
            if (!string.IsNullOrWhiteSpace(o.RadiusSourceAddress) && !GeneratorValidation.Ipv4(o.RadiusSourceAddress)) errors.Add("RADIUS source must be a configured router IPv4 address.");
            if (o.Authentication == AuthBackend.Ldap) errors.Add("This VyOS L2TP/IKEv2 template does not support direct LDAP. Use the domain's RADIUS/NPS service.");
        }
        if (o.Template == ServerTemplate.Ikev2 && o.Authentication != AuthBackend.LocalTest) errors.Add("IKEv2 RADIUS commands are not in this reviewed recipe. Use the version's official schema before migrating; no guessed commands emitted.");
        if (o.Template is ServerTemplate.Ikev2 or ServerTemplate.IpsecSiteToSite)
        {
            if (!new[] { "aes128", "aes192", "aes256", "aes128gcm128", "aes256gcm128" }.Contains(o.IkeEncryption) || !new[] { "aes128", "aes192", "aes256", "aes128gcm128", "aes256gcm128" }.Contains(o.EspEncryption)) errors.Add("Select a supported AES proposal.");
            if (!new[] { "sha256", "sha384", "sha512" }.Contains(o.IkeHash) || !new[] { "sha256", "sha384", "sha512" }.Contains(o.EspHash)) errors.Add("Select SHA-256, SHA-384 or SHA-512.");
            if (o.DhGroup is not (14 or 15 or 16 or 19 or 20 or 21)) errors.Add("Select a reviewed DH group: 14, 15, 16, 19, 20 or 21.");
        }
        return errors;
    }

    private static bool Network(string value) => GeneratorValidation.Cidr(value) && GeneratorValidation.Ipv4(Ip(value)) &&
        CidrNetwork.TryParse(value, out var network) && network.PrefixLength > 0 && value == network.ToString();

    private static string L2tp(ServerConfigOptions o, LabTopology t)
    {
        var b = Header(o, "configuration/vpn/l2tp.html");
        b.AppendLine($"set vpn ipsec interface {Q(o.ExternalInterface)}");
        b.AppendLine("set vpn l2tp remote-access ipsec-settings authentication mode 'pre-shared-secret'");
        b.AppendLine("set vpn l2tp remote-access ipsec-settings authentication pre-shared-secret '<IPSEC_PSK>'");
        b.AppendLine($"set vpn l2tp remote-access outside-address {Q(Ip(Pick(o.ExternalAddress, t.VyosExternal)))}");
        b.AppendLine($"set vpn l2tp remote-access client-ip-pool LAB-L2TP range {Q(L2tpPool(o.ClientPool, o.GatewayAddress))}");
        b.AppendLine("set vpn l2tp remote-access default-pool 'LAB-L2TP'");
        b.AppendLine($"set vpn l2tp remote-access gateway-address {Q(o.GatewayAddress)}");
        b.AppendLine("set vpn l2tp remote-access authentication protocols 'mschap-v2'");
        if (!string.IsNullOrWhiteSpace(o.DnsServer)) b.AppendLine($"set vpn l2tp remote-access name-server {Q(o.DnsServer)}");
        if (o.Authentication == AuthBackend.LocalTest)
        {
            b.AppendLine("set vpn l2tp remote-access authentication mode 'local'");
            b.AppendLine($"set vpn l2tp remote-access authentication local-users username {Q(o.Username)} password '<LOCAL_PASSWORD>'");
        }
        else
        {
            b.AppendLine($"set vpn l2tp remote-access authentication radius server {Q(o.RadiusServer)} key '<RADIUS_SECRET>'");
            b.AppendLine($"set vpn l2tp remote-access authentication radius server {Q(o.RadiusServer)} port '{o.RadiusPort}'");
            if (!string.IsNullOrWhiteSpace(o.RadiusSourceAddress)) b.AppendLine($"set vpn l2tp remote-access authentication radius source-address {Q(o.RadiusSourceAddress)}");
            b.AppendLine("set vpn l2tp remote-access authentication mode 'radius'");
        }
        b.AppendLine($"# Client split route: {Pick(o.LocalNetwork, t.VyosHq)}. Internet must remain on the client's physical adapter.");
        b.AppendLine("# Permit IKE UDP/500, NAT-T UDP/4500 and ESP to the router; UDP/1701 only with an IPsec match.");
        b.AppendLine("# Integrate these permits into your EXISTING input policy; permit only authorized pool-to-LAN forwarding.");
        b.AppendLine("# Do not copy the vendor example's Internet masquerade rule: this lab requires split tunneling.");
        b.AppendLine("# Route the client pool back through this router; first prove local login, then migrate to NPS/RADIUS.");
        b.AppendLine("# Register the router's actual source IP as an NPS client and restrict authorization to the intended AD group.");
        End(b); return b.ToString();
    }

    private static string L2tpPool(string cidr, string gateway)
    {
        // The documented explicit range is within a /24. Exclude the gateway from dynamic allocation.
        var bits = int.Parse(cidr.Split('/')[1]);
        if (bits != 24 || !GeneratorValidation.Ipv4(Ip(cidr))) throw new ArgumentException("L2TP helper currently requires an IPv4 /24 pool to generate a safe explicit client range.");
        var octets = Ip(cidr).Split('.');
        var prefix = string.Join('.', octets.Take(3));
        if (gateway == prefix + ".1") return prefix + ".2-" + prefix + ".254";
        if (!gateway.StartsWith(prefix + ".", StringComparison.Ordinal)) return prefix + ".1-" + prefix + ".254";
        throw new ArgumentException("For this /24 pool template place the PPP gateway at .1 or outside the pool; the generated range must not allocate the gateway.");
    }

    private static string WireGuard(ServerConfigOptions o, LabTopology t)
    {
        var local = Pick(o.LocalNetwork, t.VyosHq); var remote = Pick(o.RemoteNetwork, t.VyosRemote);
        var b = Header(o, "configuration/interfaces/wireguard.html"); var i = o.TunnelInterface;
        b.AppendLine($"set interfaces wireguard {i} address {Q(o.LocalTunnelAddress)}");
        b.AppendLine($"set interfaces wireguard {i} port '{o.Port}'");
        b.AppendLine($"set interfaces wireguard {i} private-key '<LOCAL_PRIVATE_KEY>'");
        b.AppendLine($"set interfaces wireguard {i} peer lab-peer address {Q(o.PeerEndpoint)}");
        b.AppendLine($"set interfaces wireguard {i} peer lab-peer port '{o.Port}'");
        b.AppendLine($"set interfaces wireguard {i} peer lab-peer public-key {Q(Pick(o.PeerPublicKey, "<PEER_PUBLIC_KEY>"))}");
        b.AppendLine($"set interfaces wireguard {i} peer lab-peer preshared-key '<WIREGUARD_PSK>'");
        foreach (var network in new[] { remote, Ip(o.PeerTunnelAddress) + (Ip(o.PeerTunnelAddress).Contains(':') ? "/128" : "/32") }.Concat(o.Routes).Distinct())
        {
            b.AppendLine($"set interfaces wireguard {i} peer lab-peer allowed-ips {Q(network)}");
            b.AppendLine($"set protocols static route {Q(network)} interface {Q(i)}");
        }
        var exemptionRule = o.NatExemptionRule;
        foreach (var destination in new[] { remote }.Concat(o.Routes).Distinct())
            NatExemption(b, o, local, destination, exemptionRule++);
        b.AppendLine($"# On the peer: reverse local/remote networks ({remote} / {local}), tunnel addresses, public endpoints and public/private key roles.");
        b.AppendLine("# Configure a matching reverse NAT exclusion on that peer. The PSK is the same on both peers.");
        b.AppendLine($"# Input: permit UDP/{o.Port} from the peer on {o.ExternalInterface}. Forward: allow both LAN directions on {i}.");
        b.AppendLine("# Extended IPsec client mode: add its actual client pool to HQ-side AllowedIPs and return routes; authorize forwarding on both routers.");
        End(b); return b.ToString();
    }

    private static string OpenVpn(ServerConfigOptions o, LabTopology t)
    {
        var b = Header(o, "configuration/interfaces/openvpn.html"); var i = o.TunnelInterface;
        b.AppendLine("# Prerequisite: import pfSense CA and the unique VyOS client certificate/private key into VyOS PKI.");
        b.AppendLine("# This is the TLS client side of the routed site-to-site service hosted by pfSense.");
        b.AppendLine($"set interfaces openvpn {i} mode 'client'");
        b.AppendLine($"set interfaces openvpn {i} device-type 'tun'");
        b.AppendLine($"set interfaces openvpn {i} protocol 'udp'");
        b.AppendLine($"set interfaces openvpn {i} remote-host {Q(o.PeerEndpoint)}");
        b.AppendLine($"set interfaces openvpn {i} remote-port '{o.Port}'");
        b.AppendLine($"set interfaces openvpn {i} persistent-tunnel");
        b.AppendLine($"set interfaces openvpn {i} tls ca-certificate {Q(o.CaName)}");
        b.AppendLine($"set interfaces openvpn {i} tls certificate {Q(o.CertificateName)}");
        b.AppendLine($"set interfaces openvpn {i} openvpn-option 'remote-cert-tls server'");
        b.AppendLine($"set interfaces openvpn {i} openvpn-option 'verify-x509-name <EXPECTED_SERVER_CERTIFICATE_CN> name'");
        b.AppendLine($"set interfaces openvpn {i} openvpn-option 'route-nopull'");
        b.AppendLine($"set protocols static route {Q(Pick(o.RemoteNetwork, t.PfSenseDmz))} interface {Q(i)}");
        NatExemption(b, o, Pick(o.LocalNetwork, t.VyosDmz), Pick(o.RemoteNetwork, t.PfSenseDmz));
        b.AppendLine("# Replace expected server CN from its verified certificate. Match data ciphers and TLS-auth/TLS-crypt to the exported profile.");
        b.AppendLine("# route-nopull prevents pushed routes/defaults from expanding this DMZ-only path; configure needed DNS explicitly.");
        b.AppendLine($"# pfSense server remote network + client-specific override for this certificate CN: {Pick(o.LocalNetwork, t.VyosDmz)}.");
        b.AppendLine($"# pfSense local/pushed network: {Pick(o.RemoteNetwork, t.PfSenseDmz)}. Permit only required DMZ-to-DMZ traffic; no redirect-gateway.");
        b.AppendLine("# Do not replace this certificate workflow with deprecated OpenVPN static-key mode.");
        End(b); return b.ToString();
    }

    private static void Proposals(StringBuilder b, ServerConfigOptions o)
    {
        b.AppendLine("set vpn ipsec ike-group LAB-IKE key-exchange 'ikev2'");
        b.AppendLine($"set vpn ipsec ike-group LAB-IKE proposal 1 dh-group '{o.DhGroup}'");
        b.AppendLine($"set vpn ipsec ike-group LAB-IKE proposal 1 encryption {Q(o.IkeEncryption)}");
        b.AppendLine($"set vpn ipsec ike-group LAB-IKE proposal 1 hash {Q(o.IkeHash)}");
        b.AppendLine("set vpn ipsec esp-group LAB-ESP pfs 'disable'");
        b.AppendLine($"set vpn ipsec esp-group LAB-ESP proposal 1 encryption {Q(o.EspEncryption)}");
        b.AppendLine($"set vpn ipsec esp-group LAB-ESP proposal 1 hash {Q(o.EspHash)}");
    }

    private static string Ikev2(ServerConfigOptions o)
    {
        if (!GeneratorValidation.Ipv4(Ip(o.ExternalAddress))) throw new ArgumentException("Enter the IKEv2 router's external IPv4 address.");
        var b = Header(o, "configuration/vpn/ipsec/remoteaccess_ipsec.html");
        b.AppendLine("# Generic IKEv2 certificate + local EAP example. This does NOT satisfy the legacy PSK/XAUTH lab requirement.");
        Proposals(b, o);
        b.AppendLine($"set vpn ipsec interface {Q(o.ExternalInterface)}");
        b.AppendLine($"set vpn ipsec remote-access pool LAB-POOL prefix {Q(o.ClientPool)}");
        if (!string.IsNullOrWhiteSpace(o.DnsServer)) b.AppendLine($"set vpn ipsec remote-access pool LAB-POOL name-server {Q(o.DnsServer)}");
        b.AppendLine($"set vpn ipsec remote-access connection LAB-RA local-address {Q(Ip(o.ExternalAddress))}");
        b.AppendLine($"set vpn ipsec remote-access connection LAB-RA authentication local-id {Q(Pick(o.ServerIdentity, Ip(o.ExternalAddress)))}");
        b.AppendLine("set vpn ipsec remote-access connection LAB-RA authentication server-mode 'x509'");
        b.AppendLine($"set vpn ipsec remote-access connection LAB-RA authentication x509 ca-certificate {Q(o.CaName)}");
        b.AppendLine($"set vpn ipsec remote-access connection LAB-RA authentication x509 certificate {Q(o.CertificateName)}");
        b.AppendLine("set vpn ipsec remote-access connection LAB-RA authentication client-mode 'eap-mschapv2'");
        b.AppendLine($"set vpn ipsec remote-access connection LAB-RA authentication local-users username {Q(o.Username)} password '<LOCAL_PASSWORD>'");
        b.AppendLine("set vpn ipsec remote-access connection LAB-RA authentication always-send-cert");
        b.AppendLine("set vpn ipsec remote-access connection LAB-RA pool 'LAB-POOL'");
        b.AppendLine("set vpn ipsec remote-access connection LAB-RA ike-group 'LAB-IKE'");
        b.AppendLine("set vpn ipsec remote-access connection LAB-RA esp-group 'LAB-ESP'");
        b.AppendLine("# Import CA/server certificate into PKI first; SAN/identity must match the Windows gateway name.");
        b.AppendLine("# Set matching Windows IKE/ESP proposals; enforce permitted routes on client and server firewall, and verify return routing.");
        End(b); return b.ToString();
    }

    private static string Ipsec(ServerConfigOptions o, LabTopology t)
    {
        if (!GeneratorValidation.Ipv4(Ip(o.ExternalAddress)) || !GeneratorValidation.Ipv4(o.PeerEndpoint)) throw new ArgumentException("This IPsec template requires distinct local/peer IPv4 addresses.");
        var b = Header(o, "configuration/vpn/ipsec/site2site_ipsec.html");
        Proposals(b, o);
        b.AppendLine($"set vpn ipsec interface {Q(o.ExternalInterface)}");
        b.AppendLine($"set vpn ipsec authentication psk LAB-PSK id {Q(Ip(o.ExternalAddress))}");
        b.AppendLine($"set vpn ipsec authentication psk LAB-PSK id {Q(o.PeerEndpoint)}");
        b.AppendLine("set vpn ipsec authentication psk LAB-PSK secret '<IPSEC_PSK>'");
        b.AppendLine("set vpn ipsec site-to-site peer LAB-PEER authentication mode 'pre-shared-secret'");
        b.AppendLine($"set vpn ipsec site-to-site peer LAB-PEER authentication local-id {Q(Ip(o.ExternalAddress))}");
        b.AppendLine($"set vpn ipsec site-to-site peer LAB-PEER authentication remote-id {Q(o.PeerEndpoint)}");
        b.AppendLine($"set vpn ipsec site-to-site peer LAB-PEER local-address {Q(Ip(o.ExternalAddress))}");
        b.AppendLine($"set vpn ipsec site-to-site peer LAB-PEER remote-address {Q(o.PeerEndpoint)}");
        b.AppendLine("set vpn ipsec site-to-site peer LAB-PEER connection-type 'initiate'");
        b.AppendLine("set vpn ipsec site-to-site peer LAB-PEER ike-group 'LAB-IKE'");
        b.AppendLine("set vpn ipsec site-to-site peer LAB-PEER default-esp-group 'LAB-ESP'");
        var local = Pick(o.LocalNetwork, t.VyosHq); var remote = Pick(o.RemoteNetwork, t.VyosRemote);
        b.AppendLine($"set vpn ipsec site-to-site peer LAB-PEER tunnel 1 local prefix {Q(local)}");
        b.AppendLine($"set vpn ipsec site-to-site peer LAB-PEER tunnel 1 remote prefix {Q(remote)}");
        NatExemption(b, o, local, remote);
        b.AppendLine("# Generic VyOS IPsec helper. The lab's IPsec site-to-site pair uses pfSense; select its checklist for that task.");
        b.AppendLine("# Match peer proposals/identities/selectors and reverse local/remote selectors on the other router.");
        b.AppendLine("# Permit UDP/500, UDP/4500, ESP and authorized inner traffic. Preserve native LAN addresses.");
        End(b); return b.ToString();
    }

    private static void NatExemption(StringBuilder b, ServerConfigOptions o, string local, string remote, int? ruleNumber = null)
    {
        var rule = ruleNumber ?? o.NatExemptionRule;
        b.AppendLine($"# NAT exclusion: reserve UNUSED rule {rule} BEFORE every matching masquerade/source-NAT rule.");
        b.AppendLine($"set nat source rule {rule} source address {Q(local)}");
        b.AppendLine($"set nat source rule {rule} destination address {Q(remote)}");
        b.AppendLine($"set nat source rule {rule} exclude");
        b.AppendLine("# This only prevents translation for the stated pair; it does not grant access. Enforce permitted scope with forwarding rules.");
        b.AppendLine("# Audit DNAT separately: constrain public-facing DNAT by inbound interface/destination so it cannot catch VPN traffic.");
    }

    private static GeneratedConfiguration PfSense(ServerConfigOptions o, LabTopology t)
    {
        var lines = PfSenseChecklist.Create(o, t);
        return new(o.Template.ToString(), string.Join(Environment.NewLine + Environment.NewLine, lines.Select((x, i) => $"[ ] {i + 1}. {x}")), ["Manual worksheet only: pfSense version and installed packages control exact field labels.", "No XML or server settings are modified."], true);
    }
}
