<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Windows-VPN</AssemblyName>
    <Product>Windows VPN Console</Product>
    <Description>VPN profiles, diagnostics and configuration helpers for Windows.</Description>
    <RootNamespace>CNIT455.VPN.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CNIT455.VPN.Core/CNIT455.VPN.Core.csproj" />
    <ProjectReference Include="../CNIT455.VPN.Providers/CNIT455.VPN.Providers.csproj" />
    <ProjectReference Include="../CNIT455.VPN.Diagnostics/CNIT455.VPN.Diagnostics.csproj" />
    <ProjectReference Include="../CNIT455.VPN.ConfigGenerators/CNIT455.VPN.ConfigGenerators.csproj" />
  </ItemGroup>
</Project>
